### ISSUE TITLE
Timing corrections

### ISSUE THREAD

**Issue by steinnymir** [momentoscope/hextof-processor#11]
Implement BAM corrections toghether with Streak Camera corrections.

The bam looks only at the FEL electron bunches timining compared to the master clock
The streak camera instead looks at interaction of laser beam with the electron bunches. This is also refreshed with much lower frequency (every few macrobunches)

In order to get pumpProbeTime correctly, both corrections need to be accounted for, and NOT just summed.

A good run to test these corrections on could be 22122, where a 1 ps shift in both BAM and streak camera appeared.

**Comment by momentoscopists** [comment]
The streak camera actually averages over about 10 ps, and drifts are typically slow. So maybe it is worth fittting/smoothing these data as a function of macrobunch for a given scan and use that for correction.
Also, we saw that the jump in the BAM correction was less than the jump in t0 in the data. So maybe there is a scaling between the BAM values and the actual arrival time jitter at the sample. This one could check by evaluating a given data set with a number of BAM scaling factors (e.g. a range from -3 -> 3) and extract the sharpness of a fast feature for each setting. Such a plot should have a minimum at the correct scaling factor.
