### ISSUE TITLE
delete lib

### ISSUE THREAD

**Issue by steinnymir** [momentoscope/hextof-processor#4]

**Comment by steinnymir** [comment]
needed to be fast... you know what to do!

**Comment by RealPolitiX** [comment]
If lib is to be cleaned, the main() in the processor should be, too

**Comment by balerion** [comment]
perhaps we should clear lib only after switching to normal mode? while this is a fork, which implies eventually calling a pull request, it might make sense keeping the legacy version, which would otherwise be lost after the pull request

**Comment by balerion** [comment]
closed by commit 79302b64c8646709349875bca5768a94bbc002aa
