### ISSUE TITLE
Improve binning performance

### ISSUE THREAD

**Issue by steinnymir** [momentoscope/hextof-processor#54]
Binning using numpy.histogramdd is quite good, but as Laurenz pointed out, this creates a strong bottleneck when binning with large number of cores. Since this is the case in Maxwell, where most of the analysis is done, we need to improve this.

An option would be to port the binning methods from MPES in here, expecially the numba based binning. 
An other would be to make a third package which would incorporate the dataframe numerical handling for both the environments, but this might be more of a long term project

**Comment by zainsohail04** [comment]
Not relevant anymore since we want to let MPES handle this.
