### ISSUE TITLE
Change from distutils to setuptools

### ISSUE THREAD

**Issue by steinnymir** [momentoscope/hextof-processor#55]
It seems that setuptools is a better choice than distutils, since it is a requirement for PyPi. So switching to it seems like the right thing to do.

**Comment by zainsohail04** [comment]
Using Cythonize, it seems, makes the build platform specifc, which I assume shouldn't be uploaded to PyPi. 
With ext_modules, building gives a wheel file named "hextof_processor-1.0.3-cp37-cp37m-linux_x86_64.whl" whereas commenting the line out gives "hextof_processor-1.0.3-py2.py3-none-any.whl". 
Build done using `python3 setup.py sdist bdist_wheel`

**Comment by steinnymir** [comment]
If thats the case, we need a different way to speed up the assignToMicrobunch function.. I can look into it, but hardly this week. There might however be some workaround. I don't believe none of the packages in pip are using cython....

**Comment by steinnymir** [comment]
it seems like it is possilble, but you need to build it on linux and windows separately... check out the answer here: https://stackoverflow.com/questions/54646403/publishing-cython-sources-for-linux-and-windows-users

**Comment by zainsohail04** [comment]
I've pushed a branch [pypi](https://github.com/momentoscope/hextof-processor/tree/pypi-build) with edits to files for building. 
I have managed to compile for linux distros. To generalize the build for all linux distros after building on my version, one has to use auditwheel. Windows should then be compiled seperately and I guess mac etc too. There's a shell script to automate the procedure of compiling and generalizing the build for all linux distros (build.sh).

I made an account on pypi test (a test repo for pypi) and uploaded the package [there](https://test.pypi.org/project/hextof-processor/0.0.1/). Currently, the emails of the authors are not complete (necessary now) and the README is not relevant for PyPi. Please suggest how to proceed.

**Comment by RealPolitiX** [comment]
On a python installation without Cython (Anaconda doesn't come with Cython installed), one gets the following error when trying to install the test-pypi version of ``hextof-processor``
```bash
ERROR: Could not find a version that satisfies the requirement Cython>=0.28.2 (from hextof-processor==0.0.1) (from versions: 0.23.4)
ERROR: No matching distribution found for Cython>=0.28.2 (from hextof-processor==0.0.1)
```

**Comment by RealPolitiX** [comment]
@zainsohail04, the author list is fine. You can add your name to it as you wish. I don't think the author email is necessary, though, it may attract unwanted emails.

**Comment by zainsohail04** [comment]
> On a python installation without Cython (Anaconda doesn't come with Cython installed), one gets the following error when trying to install the test-pypi version of `hextof-processor`
> 
> ```shell
> ERROR: Could not find a version that satisfies the requirement Cython>=0.28.2 (from hextof-processor==0.0.1) (from versions: 0.23.4)
> ERROR: No matching distribution found for Cython>=0.28.2 (from hextof-processor==0.0.1)
> ```
> 
> I suggest to remove the Cython version number in the requirements or remove the Cython entry in `requirements.txt`, and mention in the readme that Cython is required and please install beforehand.

I will make the changes and update test-pypi with this, then. Regarding emails, I had thought they were necessary but seems like not, so I will remove them.

**Comment by zainsohail04** [comment]
I've made the necessary changes. [PyPi test](https://test.pypi.org/project/hextof-processor/) versino 0.0.2. I saw that you included XPSdoniachs. Should that be part of the uploaded package?

I am guessing support for windows and mac is not so critical since maxwell runs on linux anyways. But if we need to compile for these platforms, perhaps looking into a continious integration solution is a possiblitity? I do not have all the OS to package hextof for all.

**Comment by steinnymir** [comment]
You are right, the support for Windows and mac can come at a later stage. Lets get this working on Linux first.
I think @balerion recently upgraded the XPSdoniachs functions, so having them in there would also be nice.

**Comment by RealPolitiX** [comment]
I would suggest XPSdoniachs be moved to a separate package under momentoscope. It's technically an optional part of the code, only needed when you measure core-level spectra. This way makes packaging easier.

**Comment by zainsohail04** [comment]
> I suggest to remove the Cython version number in the requirements or remove the Cython entry in `requirements.txt`, and mention in the readme that Cython is required and please install beforehand.

I have checked this now and anaconda comes with cython installed, if one creates env with anaconda dependencies:
`conda create -n <env-name> python=3.7 anaconda`
It is important the env python version corresponds to the one with which I build since the build is version specific.

Therefore, should I reinclude cython? and after a installation check from both of you, I can package the master branch and publish it on PyPi. I believe the documentation can be altered to include pip install.

Installation should take place using 
`pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple hextof-processor`
since dependencies don't exist on test pypi.

**Comment by RealPolitiX** [comment]
Sure, I suppose the push is not a big deal for now. Can you add me on PyPI (and potentially Test-PyPI) as a co-owner after you push? Follow [this](https://stackoverflow.com/questions/51890926/can-you-upload-at-pypi-with-multiple-users). My account is [here](https://pypi.org/user/realpolitix/). For others, if they have presence on PyPI, you can add similarly. Please use a sensible version number that agrees with setup.py.

**Comment by balerion** [comment]
@RealPolitiX regarding https://github.com/momentoscope/hextof-processor/issues/55#issuecomment-755265524
I would say the number of times we used the software to measure XPS peaks at FLASH would justify the inclusion of the compiled Doniach-Sunjic functions, I would honestly prioritize usability at flash rather than packaging ease, but perhaps a compromise can be found?

**Comment by zainsohail04** [comment]
> Sure, I suppose the push is not a big deal for now. Can you add me on PyPI (and potentially Test-PyPI) as a co-owner after you push? Follow [this](https://stackoverflow.com/questions/51890926/can-you-upload-at-pypi-with-multiple-users). My account is [here](https://pypi.org/user/realpolitix/). For others, if they have presence on PyPI, you can add similarly. Please use a sensible version number that agrees with setup.py.

Yes, I can do that. I already tried it with Steinn before so I remember how it works. The versioning is defined in the setup.py metadata and the same version is automatically used on the upload. 

> @RealPolitiX regarding [#55 (comment)](https://github.com/momentoscope/hextof-processor/issues/55#issuecomment-755265524)
> I would say the number of times we used the software to measure XPS peaks at FLASH would justify the inclusion of the compiled Doniach-Sunjic functions, I would honestly prioritize usability at flash rather than packaging ease, but perhaps a compromise can be found?
> 
> Can I help out with the OS support? what is technically needed? I don;t really know much about packaging

Having a seperate package still makes it quite usable. It's just a matter of using pip install twice, then. 
One needs to build the package for windows and mac on the respective systems but I think having a github Action dedicated to this would make more sense, so whenever there is a new version release, it builds for all systems (and uploads it to PyPi).

**Comment by zainsohail04** [comment]
> Sure, I suppose the push is not a big deal for now. Can you add me on PyPI (and potentially Test-PyPI) as a co-owner after you push? Follow [this](https://stackoverflow.com/questions/51890926/can-you-upload-at-pypi-with-multiple-users). My account is [here](https://pypi.org/user/realpolitix/). For others, if they have presence on PyPI, you can add similarly. Please use a sensible version number that agrees with setup.py.

I've pushed a release on the [PyPi main repository](https://pypi.org/project/hextof-processor/). However, I am not using the current version number. This is so we can perhaps change the documentation on the PyPi page (it doesn't need the instructions for forking repo etc.) and to decide if we are including XPSdoniachs package. If I had put the correct version, we would have to update it to a higher version in case we wanted to push the above mentioned changes.

I've invited you and Steinn as owners.
