### ISSUE TITLE
Delete all branches except master for LFS integration

### ISSUE THREAD

**Issue by zainsohail04** [momentoscope/hextof-processor#70]
I deleted the branches I had on the repo and I believe Steinn deleted some too. There's still two branches here. Is it possible to delete them?

**Comment by steinnymir** [comment]
Today I also deleted all branches which were already merged, or were too old and did not contain useful additions . I wrote to @Jus80687 to ask about the branch Scholz2018 as it was created for one of his beamtimes. If he gives the go, you can close it .

The last one is the work @balerion was doing on the orthoslices visualizer. I don't know the state of it, but maybe we could copy th changes and create a new branch with these after the LFS fix?

**Comment by steinnymir** [comment]
The Scholz2018 branch is gone, last one standing is the orthoslices one, which is up to @balerion to decide how to handle it (merge or delete).

**Comment by balerion** [comment]
It's gone

**Comment by zainsohail04** [comment]
The task was done
