### ISSUE TITLE
Change in path structure

### ISSUE THREAD

**Issue by MichaelHeber** [momentoscope/hextof-processor#87]
for the Laser stability tests the raw data path was:
/asap3/fs-flash-o/gpfs/hextof/2021/data/11013350/raw/hdf/FL1USER3/

path sturctute is differnt to before
beamptimepath/raw/hdf/express/

maybe it would be helpful to make the raw path accessible with out using
"prc.raw_dir='/asap3/fs-flash-o/gpfs/hextof/2021/data/11013350/raw/hdf/FL1USER3/' "
in between

There is also pairs of similar attributes like:
"prc.raw_dir" coming from the express read in
"prc.DATA_RAW_DIR" from the settings file

**Comment by zainsohail04** [comment]
- Change path structure to the new one
  - Check if there is an express folder or daq folder
- Keep it compatible with the last months
- Include daq in settings files
